spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MapPlan
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


file:
  dir: C:/Users/kyj20/Desktop/flabproject/ProjectFile/

logging.level:
  org.hibernate.SQL: debug


server:
  address: localhost

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-ll5va.pub-cdb.ntruss.com:3306/studyCloud?useSSL=false&serverTimezone=UTC
    username: test
    password: test123!
  s3:
    accessKey: 1m4B4ebcg75bNqkV29XT
    secretKey: ms4wULSDm9WQnJxMH9vuXSuM09QQR1DLtLIxwees
    bucketName: projectbucket
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug

server:
  address: localhost